### ISSUE TITLE
build JSON file, use timestamp in seconds since 1970 instead of full date format

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#110]
In the `[build_number].json` it seems like currently we store `"2018-01-30 16:24:23 -0500"` for time stamps, however I think we should use `1516639255` instead 👍

**Comment by SumLare** [comment]
Are PR's on some issues welcomed here?

**Comment by revolter** [comment]
@SumLare, More than welcomed 😃

**Comment by taquitos** [comment]
💯 we'd love it if you wanted to tackle some! Check out our contributing doc: https://github.com/fastlane/ci/blob/master/CONTRIBUTING.md#before-you-start

**Comment by KrauseFx** [comment]
Yep, un-assigned myself, feel free to grab this one 👍

**Comment by minuscorp** [comment]
I've been digging into this issue, and I can't find where you're stablishing that format when converting to json the `Time` object of a build, referencing the docs:

> `to_json(*args) public`
Stores class name (Time) with **number of seconds since epoch** and number of microseconds for Time as JSON string

**Comment by KrauseFx** [comment]
I haven't looked into the code base yet for this one, but from what I remember, in `JSONConvertible` we iterate over all available attributes, and just directly access the `instance_variable_value`. What that means is that we basically just convert the `Time` object to a String. We don't have support for conversions of formats on saving/loading

**Comment by minuscorp** [comment]
So I'm thinking of adding an argument to the convertible, a hash in a `key => proc` form in order to customize the output of the different conversions. Should I open a PR covering this?😊 (You can assign it to me)

**Comment by KrauseFx** [comment]
So I'm not too familiar with `JSONConvertible` - I think a proc might work, but maybe we could do something alone the lines of defining a mapping for each attribute? So that a class can define, this `attr_accessor` is of type `Time`, but here's a method to convert it to/from it

**Comment by minuscorp** [comment]
But I'm that case the `json_convertible` would know about the methods in the model itself and then they're coupled? Or you're talking about overriding the setters and getters in the class with the custom if seconds from epoch convert to `Time`, else set it normally, and the getter is always the seconds from epoch? Or just I'm missing something about your point. 😅

**Comment by KrauseFx** [comment]
Ahh, good point, I got it wrong, ignore my last comment. Maybe let's wait for @taquitos to chime in on this one 👍

**Comment by taquitos** [comment]
Yeah, I was thinking that we could add some extra methods to `JSONConvertible`:
`self.attribute_key_name_map` : A map of Ruby attribute names to json key names for times when a key in your model should be named differently in the resultant JSON.

And, more importantly, I think @minuscorp and I are on the same page with this:
`self.attribute_name_to_json_proc_map` : a map of ruby attribute names to proc, so that when you are going to transcode the value into json, it grabs a proc that can do custom processing. 

So, each of these methods would have a basic implementation on `JSONConvertible` but then, when you need to use them you'd update the corresponding mixin, using the adaptor pattern so that we don't need to change the underlying model class.

For example, in `json_build_data_source.rb` you can update the mixin to implement these methods (actually, pulling out the mixin to it's own file would be ideal at this point, since it's sufficiently large now that we're adding more to it)

So I was thinking something like:
```ruby
class Build # this is the mixin as seen in `json_build_data_source.rb`
  include FastlaneCI::JSONConvertible

  # class method
  def self.attribute_name_to_json_proc_map
    timestamp_to_json_proc = proc { |timestamp|
      return timestamp.strftime('%Q')
    }
    return { "timestamp" => timestamp_to_json_proc }
  end
end
```
 then in `JSONConvertible`, you'd need to update `to_object_dictionary(ignore_instance_variables: [])` to look into this mapping and then call the proc with the proper attribute value.

If that sounds like what you were thinking 🎈:goat:

**Comment by minuscorp** [comment]
I'll take a look to this tomorrow and Monday and try to setup a PR for this upcoming week 👨🏻‍💻

**Comment by minuscorp** [comment]
So if `def self.attribute_name_to_json_proc_map` is needed, then `def self.attribute_json_to_name_proc_map` is mandatory, didn't it? Without that method, the `JSONConvertible` wouldn't know how to map back to the ruby value from the json.

**Comment by minuscorp** [comment]
#118 🚀
