### ISSUE TITLE
Sinatra doesn't seem to like a trailing `/`

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/ci#15]
```
http://127.0.0.1:8080/login/
```
is treated differently than
```
http://127.0.0.1:8080/login
```

That's not how most web services work AFAIK, and we should strip trailing `/`

**Comment by snuggs** [comment]
@KrauseFx most web services may do this but if it isn't with a 301 redirect it's creating [duplicate content](https://support.google.com/webmasters/answer/66359) as they are indeed both two separate resources. That's the R and the I in URI. They MUST be unique. (Even if you redirect). If they are not must redirect or use `<link rel=canonical...>`.

To be clear even Roy Fielding said Rails didn't implement REST properly and spent [months in endless debates with the man](https://github.com/rails/rails/pull/505#issuecomment-3181362). But [if you asked Rails at that time](http://weblog.rubyonrails.org/2012/2/26/edge-rails-patch-is-the-new-primary-http-method-for-updates/) it would have been said they WERE RESTful. Technically speaking until browsers support DELETE,PUT,PATCH there's no framework really restful. But I digress. `/foo` and `/foo/` are two different resources. Hence the need to redirect. In actuality [this test](https://github.com/sinatra/sinatra/pull/1273/files#diff-2331f5ce4d3fe6caf03ad0e1e783e574R1503) SHOULD respect both resources and perhaps perform a redirect. An additional can of worms is opened re: non-safe methods.

**Comment by KrauseFx** [comment]
That's super interesting, thanks for the comment and letting us know @snuggs 👍 

As a developer, it's common to modify the URL directly - and as a result often end up with a trailing `/`. 

While not considering this might be 100% correct and according to the specifications, I don't see a reason why we should distinguish, considering that we'll never show different content depending on if there is a trailing `/` or not

**Comment by snuggs** [comment]
it's not about different content. It's more about unloading developer footguns. INDEED there are many apps where people use relative urls. Some even merely render html from Sinatra which isn't  a bad thing. But if one of those links somehow links to `/users` and the view links to `cat.jpg` it won't come from the `/users` folder. Again I will state Sinatra perhaps is shielded from this by the convention of serving static from `/public` or wherever. But this is more a discussion of how the web was intended to work, and where devs chose ergonomics over UI/UX.  Now i'm as lazy as any other developer. But must admit we do load personal footguns up from time to time. The next generation will deal with it. I need to :shipit: 🚢 " is the mantra. Still doesn't mean it's right. 

To be clear i'm not suggesting anything I just know with working on the platform specs that devs may run the code. But forget that the people run the URIs. Someone bookmarks a link to `/users` and another links to `/users/` if Sinatra is doing the trimming behind the scenes now the dev is FORCED to use `<link rel=canonical href=/users>` in their code or Google will actually downvote that resource. We often don't find out until the SEO strategist on the team comes barking at our desk. That's if we still work there. And why she is pissed is because she can't do her job as well as she thought.

Not bringing up for-instances. This actually happened to me.

#SadButTrue

What do you think we should do? I'm not suggesting anything as you influence direction more than I do. I just stumbled across this searching for [what is the right 405 for resources](https://github.com/devpunks/snuggsi/pull/164).

At minimum if a redirect is not done perhaps documentation of sorts respectively. And of course I wouldn't suggest something I'm not willing to contribute to myself. I'd just be a curmudgeon then. Open source has enough of this already. :-)

Happy Friday!

**Comment by tmornini** [comment]
@snuggs said:

> until browsers support

I think you mean:

> until HTML supports

😄

**Comment by snuggs** [comment]
Indeed @tmornini ... indeed!

**Comment by tmornini** [comment]
@snuggs said:

> The link example should also have been cat.**gif**

¿Por que?
