### ISSUE TITLE
Artifact provider stores local path with username

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#599]
We want to store `local_repo_path` in a way that allows us to only store the relevant part of the path. Example:
We have this in `repo_config`:
`"local_repo_path": "/Users/jliebowitz/.fastlane/ci/86286442-360f-4b9f-8e2b-d60cd0f257e7",`

but it should be 
`"local_repo_path": "86286442-360f-4b9f-8e2b-d60cd0f257e7",`
Since the rest of it can be derived.

**Comment by taquitos** [comment]
Reason being, when we use the same `ci-config` repo during testing, my user can change, and then storing artifacts fails.

**Comment by minuscorp** [comment]
Technically the whole path should be stored, because the user may not use the `default_root_path` and use another one, that's why we need the whole path string, which I can do is to change the storage to a global directory (i.e. `/var...`) but dunno, will keep it as it is because of that, the `ArtifactProvider` needs to know how to find the artifact in its global context.

**Comment by KrauseFx** [comment]
So what we were thinking is that we have a working directory for fastlane.ci, currently being `~/.fastlane/ci`. This might change in the future, but it's generally called a working directory.

**Comment by minuscorp** [comment]
What I meant is that the user might create a `LocalArtifactProvider` with a custom `root_path` different from `~/.fastlane/ci`, that's why I needed the whole path instead of just the relative path from the `~/.fastlane/ci` path.

**Comment by KrauseFx** [comment]
For now let's assume the `LocalArtifactProvider` can only store things inside the fastlane working directory 👍

**Comment by KrauseFx** [comment]
We can close this one, right?

**Comment by minuscorp** [comment]
Awwwwwww yeah
