### ISSUE TITLE
No Private Repo's Results In 500 Error

### ISSUE THREAD

**Issue by jwelton** [fastlane/ci#640]
If you try and go through the on boarding flow, without the ability to create any private repo's on your GitHub.com account, then you get an 500 internal server error.

I'm thinking perhaps this should be changed to give the user a more friendly message?

This is the error from the console:
`Octokit::UnprocessableEntity - POST https://api.github.com/user/repos: 422 - Please upgrade your plan to create a new private repository. // See: https://github.com/pricing:`

**Comment by KrauseFx** [comment]
Thanks for reporting, yes definitely something we'll have to handle 👍 To start using fastlane.ci, can you upgrade your account and give it another shot?

**Comment by taquitos** [comment]
We encrypt all the important bits using the key from `FASTLANE_CI_ENCRYPTION_KEY` RSA256-CBC (using SHA256 digest) BUT I like to rotate my keys so I'm ok with keeping my config repo public.

So like @KrauseFx mentioned, I still think people shouldn't make it public if they can help it. While RSA256 is supposedly unbreakable, and we're using the SHA256 digest on the key, it could still, theoretically contain a backdoor/bug that makes brute forcing possible.

**Comment by jwelton** [comment]
Sorry about the late reply on this. So its kind of more annoying because its attempting to create a private repo under the bot account. Thing is, I think for most people the bot account won't have any private repo's, as chances are they're not paying a subscription on that account. I guess things might be a little different if using an organisation account though 🤔

Perhaps it would be good to give an option to specify an already created repo. This way, I would be able to create a private repo under my account and give my bot account collaborator access to it?

**Comment by KrauseFx** [comment]
Oh wow, that's a great point, the bot account will never have a paid GitHub plan. Ok so how about this: we don't ever create a repo for the user, but instead tell the user to create one, grant access to the bot, and provide the URL? We verify that's it's a GitHub URL (for now) and go from there

**Comment by jwelton** [comment]
I think thats a good solution @KrauseFx 👍

**Comment by AndrewMcBurney** [comment]
The credentials that we're using in the [configuration repository service](https://github.com/fastlane/ci/blob/master/app/services/configuration_repository_service.rb#L19) are the clone user's credentials: [[1]](https://github.com/fastlane/ci/blob/master/app/services/services.rb#L173), [[2]](https://github.com/fastlane/ci/blob/master/app/services/services.rb#L104-L108).

I just went through the onboarding to verify. It did create the repository in the clone user's account, however it failed due to #607.

What I think is causing this to fail is that the bot user account doesn't have access to the private configuration repository, thus when it tries to clone it, it can't find the repo.

This is a regression, because when I initially wrote this part of onboarding it would both create and clone the repo using the clone user's API token.

**Comment by taquitos** [comment]
So, I think to summarize what we can do is the following:

1. Create the repo if it doesn't exist, using the user's credentials
2. Use https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator to grant the bot account access
3. Clone the repo using the bot account

We want to use the bot account for as much of this stuff as possible.

**Comment by minuscorp** [comment]
Maybe I'm too late for the discussion about this (and ignore the message if it is), but I kind of like the idea of auto-creating the (I'm in the case that there's no ci-config repo in the user's account yet) repo using the following logic:
1. Insert repo name.
2. Choose for either private or public repo (a combo box).
3. Try to create it.
    - If success, great, go ahead.
    - If failed with `Octokit::UnprocessableEntity`, ask for fallback to public repo.
    - If failed for other reason, rescue properly.
