### ISSUE TITLE
Setup PR bot for `needs attention` on PRs that are older than 1 week

### ISSUE THREAD

**Issue by taquitos** [fastlane/ci#971]
Like in the fastlane repo, we should have a PR bot that flags PRs that are older than 1 week with the `needs attention` label

**Comment by KrauseFx** [comment]
This is great, I'd love that. Instead of using our custom fastlane `issue-bot`, let's be fancy and use the brand new peril (maybe soon we'll even get peril as a service) 👍 

We already have a [peril-settings](https://github.com/fastlane/peril-settings) repo in our org, and a bot that runs those rules for us. Right now we only use it for regression detection 👍 

cc @orta

**Comment by orta** [comment]
Yeah, you could:

a) add a scheduled task (you'd need to add a mongo instance to your peril, or switch to my peril staging) ([settings.json](https://github.com/artsy/peril-settings/blob/master/peril.settings.json#L25-L31) [example task](https://github.com/artsy/peril-settings/blob/master/tasks/daily-license-check.ts)

b) find an event to run the check on every so often, maybe on a new tag being created?
